[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(message)s
log_auto_indent = false
markers =
    single_recipe: tests for a single recipe
    multiple_recipes: tests for multiple recipes
    multiple_recipes_hbm: tests for hierarchical preference model with multiple recipes
    multiple_humans: tests with multiple humans (different hidden HBMs) to show personalization