[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(message)s
log_auto_indent = false
show_capture = no
markers =
    single_recipe: tests for a single recipe
    multiple_recipes: tests for multiple recipes