"""
recipes.py
Central repository for symbolic cooking recipes
10/08/2025
-- Recipes generated by ChatGPT
"""

from multitask_personalization.envs.spices.spices_env import RecipeSpec, ProfileSpec

SIMPLE_DAL = RecipeSpec(
        name="simple_dal",
        spices=("cumin", "mustard", "turmeric", "chili", "garam_masala"),
        predecessors={
            "cumin": (),
            "mustard": ("cumin",),
            "turmeric": ("mustard",),
            "chili": ("turmeric",),
            "garam_masala": ("chili",),
        },
    )

BREAKING_BREAD = RecipeSpec(
    name="BreakingBread",
    spices=("salt", "pepper", "sugar", "flour"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "sugar": ("pepper",),
        "flour": ("sugar",),
    },
)

SPICY_SALSA = RecipeSpec(
    name="SpicySalsa",
    spices=("salt", "pepper", "garlic", "tomato"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "garlic": ("pepper",),
        "tomato": ("garlic",),
    },
)

SWEET_CURRY = RecipeSpec(
    name="SweetCurry",
    spices=("salt", "pepper", "sugar", "turmeric", "cinnamon", "onion"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "sugar": ("pepper",),
        "turmeric": ("pepper",),
        "cinnamon": ("sugar",),
    },
)

GRANDMAS_SOUP = RecipeSpec(
    name="GrandmasSoup",
    spices=("salt", "pepper", "garlic", "onion", "carrot", "celery", "potato"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "garlic": ("pepper",),
        "onion": ("garlic",),
        "carrot": ("onion",),
        "celery": ("carrot",),
        "potato": ("celery",),
    },
)

MEDITERRANEAN_FEAST = RecipeSpec(
    name="MediterraneanFeast",
    spices=("salt", "pepper", "basil", "olive_oil"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "basil": ("pepper",),
        "olive_oil": ("basil",),
    },
)

ULTRA_COMPLEX_FEAST = RecipeSpec(
    name="UltraComplexFeast",
    spices=(
        "salt", "pepper", "olive_oil", "onion", "garlic", "ginger",
        "turmeric", "cumin", "coriander", "tomato", "chili", "paprika",
        "cinnamon", "clove", "bay_leaf", "yogurt", "honey", "mint"
    ),
    predecessors={
        # base seasoning chain
        "salt": (),
        "pepper": ("salt",),

        # aromatic base
        "olive_oil": ("salt",),
        "onion": ("olive_oil",),
        "garlic": ("onion",),
        "ginger": ("onion",),

        # spice fusion branch
        "turmeric": ("garlic", "ginger"),
        "cumin": ("turmeric",),
        "coriander": ("turmeric", "cumin"),
        "chili": ("coriander", "pepper"),
        "paprika": ("chili", "coriander"),

        # sweet–warm branch
        "cinnamon": ("turmeric",),
        "clove": ("cinnamon",),
        "bay_leaf": ("clove", "cumin"),

        # base integration
        "tomato": ("coriander", "onion"),
        "yogurt": ("tomato", "bay_leaf"),
        "honey": ("yogurt", "paprika"),

        # finishing
        "mint": ("honey", "pepper", "yogurt"),
    },
)

# Profiles

CHEF_A = ProfileSpec(
    name="ChefA",
    recipes=("SimpleDal", "BreakingBread", "SpicySalsa", "SweetCurry", "GrandmasSoup", "MediterraneanFeast"),
)

CHEF_B = ProfileSpec(
    name="ChefB",
    recipes=("SimpleDal", "BreakingBread", "SpicySalsa", "SweetCurry", "GrandmasSoup", "MediterraneanFeast"),
)

# RECIPE LOOKUP
# # ---------------------------------------------------------------------------

ALL_RECIPES = {
    "SimpleDal": SIMPLE_DAL,
    "BreakingBread": BREAKING_BREAD,
    "SpicySalsa": SPICY_SALSA,
    "SweetCurry": SWEET_CURRY,
    "GrandmasSoup": GRANDMAS_SOUP,
    "MediterraneanFeast": MEDITERRANEAN_FEAST,
    "UltraComplexFeast": ULTRA_COMPLEX_FEAST,
}

def get_recipe(name: str) -> RecipeSpec:
    """Retrieve a recipe by name."""
    if name not in ALL_RECIPES:
        raise ValueError(f"Unknown recipe name: {name}")
    return ALL_RECIPES[name]

def list_recipes():
    """List all available recipe names."""
    return list(ALL_RECIPES.keys())

# PROFILE LOOKUP
# # ---------------------------------------------------------------------------

ALL_PROFILES = {
    "ChefA": CHEF_A,
    "ChefB": CHEF_B,
}


def get_profile(name: str) -> ProfileSpec:
    """Retrieve a profile by name."""
    if name not in ALL_PROFILES:
        raise ValueError(f"Unknown profile name: {name}")
    return ALL_PROFILES[name]

def list_profiles():
    """List all available profile names."""
    return list(ALL_PROFILES.keys())

if __name__ == "__main__":
    print("Available recipes:")
    for r in list_recipes():
        print(" -", r)

    recipe = get_recipe("SweetCurry")
    print("\nLoaded recipe:", recipe.name)
    for s, nxt in recipe.predecessors.items():
        print(f"  {s} -> {nxt}")
