"""
recipes.py
Central repository for symbolic cooking recipes
10/08/2025
-- Recipes generated by ChatGPT
"""

from multitask_personalization.envs.spices.spices_env import RecipeSpec

SIMPLE_DAL = RecipeSpec(
        name="simple_dal",
        spices=("cumin", "mustard", "turmeric", "chili", "garam_masala"),
        predecessors={
            "cumin": (),
            "mustard": ("cumin",),
            "turmeric": ("mustard",),
            "chili": ("turmeric",),
            "garam_masala": ("chili",),
        },
    )

BREAKING_BREAD = RecipeSpec(
    name="BreakingBread",
    spices=("salt", "pepper", "sugar", "flour"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "sugar": ("pepper",),
        "flour": ("sugar",),
    },
)

SPICY_SALSA = RecipeSpec(
    name="SpicySalsa",
    spices=("salt", "pepper", "garlic", "tomato"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "garlic": ("pepper",),
        "tomato": ("garlic",),
    },
)

SWEET_CURRY = RecipeSpec(
    name="SweetCurry",
    spices=("salt", "pepper", "sugar", "turmeric", "cinnamon", "onion"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "sugar": ("pepper",),
        "turmeric": ("pepper",),
        "cinnamon": ("sugar",),
    },
)

GRANDMAS_SOUP = RecipeSpec(
    name="GrandmasSoup",
    spices=("salt", "pepper", "garlic", "onion", "carrot", "celery", "potato"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "garlic": ("pepper",),
        "onion": ("garlic",),
        "carrot": ("onion",),
        "celery": ("carrot",),
        "potato": ("celery",),
    },
)

MEDITERRANEAN_FEAST = RecipeSpec(
    name="MediterraneanFeast",
    spices=("salt", "pepper", "basil", "olive_oil"),
    predecessors={
        "salt": (),
        "pepper": ("salt",),
        "basil": ("pepper",),
        "olive_oil": ("basil",),
    },
)

# RECIPE LOOKUP
# # ---------------------------------------------------------------------------

ALL_RECIPES = {
    "SimpleDal": SIMPLE_DAL,
    "BreakingBread": BREAKING_BREAD,
    "SpicySalsa": SPICY_SALSA,
    "SweetCurry": SWEET_CURRY,
    "GrandmasSoup": GRANDMAS_SOUP,
    "MediterraneanFeast": MEDITERRANEAN_FEAST,
}

def get_recipe(name: str) -> RecipeSpec:
    """Retrieve a recipe by name."""
    if name not in ALL_RECIPES:
        raise ValueError(f"Unknown recipe name: {name}")
    return ALL_RECIPES[name]

def list_recipes():
    """List all available recipe names."""
    return list(ALL_RECIPES.keys())

if __name__ == "__main__":
    print("Available recipes:")
    for r in list_recipes():
        print(" -", r)

    recipe = get_recipe("SweetCurry")
    print("\nLoaded recipe:", recipe.name)
    for s, nxt in recipe.predecessors.items():
        print(f"  {s} -> {nxt}")
